GET http://localhost:8000/products/ HTTP/1.1

###
POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0Nzc3MDUyLCJpYXQiOjE3NjQ3NzY3NTIsImp0aSI6IjM4N2U4MzU5ODlmZDQ2NDQ4NGFjY2MzY2VjNTM1NDIyIiwidXNlcl9pZCI6IjEifQ.fvTsH-qxP9xdZskqrWmgzX05GEMXlJdxL_n_EaewE30

{
  "name": "Flat Screen Television",
  "price": 3000.00,
  "stock": 14,
  "description": "An amazing new TV"
}

###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
  "username": "john-doe",
  "password": "password"
}